import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google'

const monserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monserrat.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
